### PR TITLE
Adding relative path handling for postbody files

### PR DESCRIPTION
**Pull request by jimbobmcgee**
My attempts to resolve the issue/change-request I raised, regarding inconsistent handling of paths: https://github.com/sni/Webinject/issues/26

1. Altered `_read_config_xml` to look for a config.xml file in the same place as webinject.pl, if `-c` is not supplied and config.xml is not found in the current working directory.  Behaviour is unchanged, where `-c` is specified.
2. Altered `_httppost_xml` to look for postbody external files in a directory relative to the test case xml file or, if not found, relative to webinject.pl.
3. Added `postbodybasedir` config parameter to override new relative path handling in `_httppost_xml`, so reversion to old behaviour is straightforward.

For instance, given a test case in `/var/test-cases/testcase01.xml`:
````
<testcases repeat="1">
<case
    id="1"
    description1="Get UID"
    url="http://{BASEURL}:8002/Foo.svc"
    method="post"
    posttype="text/xml"
    addheader="SOAPAction: http://foo/bar/GetUID"
    postbody="file=>API-post-GetUID.xml"
    logresponse="yes"
/>
</testcases>
````

Original behaviour:
* `[me@localhost /]$ /pathto/webinject.pl /var/test-cases/testcase01.xml`
   `ERROR: Failed to open text/xml file API-post-GetUID.xml`
   *(API-post-GetUID.xml is expected to be at `/API-post-GetUID.xml`)*

* `[me@localhost /tmp]$ /pathto/webinject.pl /var/test-cases/testcase01.xml`
   `ERROR: Failed to open text/xml file API-post-GetUID.xml`
   *(API-post-GetUID.xml is expected to be at `/tmp/API-post-GetUID.xml`)*

New behaviour:
* `[me@localhost /]$ /pathto/webinject.pl /var/test-cases/testcase01.xml`
   `WebInject OK...`
   *(API-post-GetUID.xml is expected to be at `/var/test-cases/API-post-GetUID.xml`)*

* `[me@localhost /tmp]$ /pathto/webinject.pl /var/test-cases/testcase01.xml`
   `WebInject OK...`
   *(API-post-GetUID.xml is expected to be at `/var/test-cases/API-post-GetUID.xml`)*

Reversion to old behaviour:
* `[me@localhost /]$ /pathto/webinject.pl -s postbodybasedir=. /var/test-cases/testcase01.xml`
   `ERROR: Failed to open text/xml file API-post-GetUID.xml (resolved to /API-post-GetUID.xml)`
   *(API-post-GetUID.xml is expected to be at `/API-post-GetUID.xml`)*

### CODE REVIEW

**Comment by sni** [comment]
I'll be good with this patch but please:
 - remove debug code
 - don't change the version, i will do that on the actual release
 - add postbodybasedir to the pod documentation

**Comment by jimbobmcgee** [comment]
Those changes should be in place, now.  If you need anythign further, please let me know.

**Comment by sni** [comment]
Thanks, merged

**Comment by jimbobmcgee** [comment]
Cool. Out of interest, what's your release cycle...?

**Comment by sni** [comment]
There is no release cycle since webinject hardly changes in the last years. I will cut a release now.

**Pull request merged**
