### PR TITLE
Added missing LICENSE meta.

### PR DESCRIPTION
**Pull request by manwar**
Hi @sni 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by sni** [comment]
Thanks, but Module::Install complains about:
```Invalid LICENSE value 'gpl_2' ignored```

**Comment by manwar** [comment]
> Thanks, but Module::Install complains about:
> `Invalid LICENSE value 'gpl_2' ignored`

manwar@ubuntu:~/github/Webinject/Webinject$ perl Makefile.PL 
include /home/manwar/github/Webinject/Webinject/inc/Module/Install.pm
include inc/Module/Install/Metadata.pm
include inc/Module/Install/Base.pm
include inc/Module/Install/Makefile.pm
Cannot determine license info from lib/Webinject.pm
include inc/Module/Install/Scripts.pm
include inc/Module/Install/ReadmeFromPod.pm
readme_from lib/Webinject.pm to txt
include inc/Module/Install/AutoInstall.pm
include inc/Module/Install/Include.pm
include inc/Module/AutoInstall.pm
*** Module::AutoInstall version 1.16
*** Checking for Perl dependencies...
[Core Features]
- LWP                   ...loaded. (6.26)
- XML::Simple           ...loaded. (2.22)
- HTTP::Request::Common ...loaded. (6.18)
- HTTP::Cookies         ...loaded. (6.01)
- Time::HiRes           ...loaded. (1.9758)
- Getopt::Long          ...loaded. (2.48)
- Net::SSLeay           ...loaded. (1.58)
- IO::Socket::SSL       ...loaded. (2.048)
- XML::Parser           ...loaded. (2.44)
- Error                 ...loaded. (0.17010)
- File::Temp            ...loaded. (0.2304)
- URI                   ...loaded. (1.71)
*** Module::AutoInstall configuration finished.
include inc/Module/Install/WriteAll.pm
include inc/Module/Install/Win32.pm
include inc/Module/Install/Can.pm
include inc/Module/Install/Fetch.pm
Generating a Unix-style Makefile
Writing Makefile for Webinject
Writing MYMETA.yml and MYMETA.json
Writing META.yml
manwar@ubuntu:~/github/Webinject/Webinject$

**Comment by manwar** [comment]
And I do get LICENSE nicely as below:


  ],
  "dynamic_config" : 0,
  "generated_by" : "ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010",
  "license" : [
     "gpl_2"
  ],
  "meta-spec" : {

**Comment by sni** [comment]
strange, seems like it doesn't recognize any license here.

**Comment by sni** [comment]
thanks and merged.

**Pull request merged**
